backend:
  image:
    repository: zaidaftab/talentsphere-backend
    tag: latest

frontend:
  image:
    repository: zaidaftab/talentsphere-frontend
    tag: latest

mysql:
  image:
    repository: mysql
    tag: "8.4"

  rootPassword: root123
  database: talentsphere

ingress:
  enabled: true

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 70
