apiVersion: apps/v1
kind: Deployment

metadata:
  name: talentsphere-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: talentsphere-backend

  template:
    metadata:
      labels:
        app: talentsphere-backend

    spec:
      containers:
      - name: talentsphere-backend

        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/talentsphere

        - name: SPRING_DATASOURCE_USERNAME
          value: root

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
